Jackson Mowry
Profressor Colby
NUTR216
2021-11-22

* Name of Food:
Fenugreek
* Food Facts:
Fenugreek is a crop grown worldwide, though its cullinary uses are linked to India. Both the seeds and the leaves are used in cooking. Its genus Trigonella is a member of the Fabaceae family. Therefore its scientific name is: Trigonella foenum-graecum.
The chemical compound that porduces the strong smell of fenugreek is named Sotolon. This compound is highly aromatic and is present in fake maple syrup and fenugreek. Given this similarity people are often reminded of maple syrup whe consuming large portions of fenugreek.
* Historical and Cultural Facts
It is commonly used in triditional medicine with not proven benefits. Its uses as a dietary supplement is also not proven to be effective. In certain individuals its use may even trigger an anaflactic shock.
The crop wa domesticated in Asia and has since spread all over the world. Although th first account of the crop in wriritng occurs around 1 A.D., seeds have been found dating back to as far as 4000 B.C. If you go back to the origins of its name it turns out th the crop was once called greek hay.
* Nutrient Composition: per 100g
Calories: 323 kcal, Carbohydrates: 58g, Fiber: 25g, Fat: 6.4g, Protein: 23g
B1: 0.3mg, B2: 0.3mg, B3: 1.64mg, B6 0.6mg, B9: 57 micrograms, C 3mg
Calcium: 176mg, Iron: 34mg, Magnesium: 191mg, Manganese: 1.23mg, Phosphorus: 296mg, Potassium: 770mg, Sodium: 67mg, Zinc: 2.5mg (USDA)
* Relationship with Disease
Fenugreek is not safe for pregnant or nursing women as this plant has negative side effects on the body. These effects may be mild like cramps, while others may experience a miscariage from the consumption of fenugreek. Fenugreek also causes alergic reactions ranging from diarrhea, to bloating of the stomach. The plant may also have negative effects on those who take medicine for diabetes, or other blood medications. There is no current evidence that fenugreek has any positive health effects.
* Agricultural Information:
Although this crop can be grown worldwide that majority is still produced in India, producing 80% of the worlds fenugreek. The fenugreek plant stands at 20in tall, and green in color. During the spring the plant may have white flowers that turn into pods which contain fenugreek seeds. The crop can be grown year round but needs speical attention to avoid possible frost damage or death.
* Selection and Storage:
The fenugreek plant undergoes manual harvesting after the pods change in color. After harvesting the plant will either be dried in bundles or transported to its final destination fresh. When harvested for their seeds the pods must be seperated from the plant, which can then udergo further porcessing to seperate the seeds.
* Preperation:
Fenugreek is used in both fresh and dried forms in various dishes. Both hot and cold dishes can be prepared with fenugreek. The leaves are used in salads, or sprouts of fenugreek. While fresh leaves can be used cold th dried leaves are used in soups or curry much the same way as you or I would use dried herbs.
On the other hand the seeds are used more triditionally as spices. Both ground and whole seeds can be used in various dishes, from meat coatings, to hot drinks, to broths. Other cultures may bake with the seeds encorporating them into bread.
* Cultural Dish:
Pastirma is a meat dish consisting of a spice rub and cured beef. The meat is first rinsed off before salt is applied, then the meat is allowed to dry for the first drying time. After this period the meat is pressed in order to extract even more water, and finally it is pressed once more with a hot press. Then the meat is coated with a spice rub called cemen, which contains fnugreek, garlic, and chili powder. This spice mix dyes the meat a deep red.
